# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sohair Ahmad
email: sohair1991@gmail.com
profile_picture: https://www.gravatar.com/avatar/55f58f4a7e64e4c118a1de7ffcc2681d.jpg?s=250
# cover_image: https://www.gravatar.com/avatar/55f58f4a7e64e4c118a1de7ffcc2681d.jpg?s=250
description: >- # this means to ignore newlines until "baseurl:"
  Personal website, portfolio of Sohair Ahmad, software developer, technical lead and people manager
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima-bootstrap
plugins:
  - jekyll-feed

header_pages:
- resume.md
- about.md

# minima-bootstrap settings
twitter_username: iamsohair
github_username:  Sohair63
linkedin_username: sohair-ahmad
instagram_username: isohairahmad
show_twitter_feed: true
twitter_feed_setting: 'noheader, noscrollbar, nofooter, noborders'
tweets_limit: 3
twitter_ref_src: iamsohair?ref_src=twsrc%5Etfw

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
